name: Feature request
description: Suggest an idea for the game
title: "[Feature]"
labels: ['Type: Feature']
body:
  - type: checkboxes
    attributes:
      label: There is no other issue with the same feature request.
      description: Please take some time and try to find another issue with the same feature request you encountered.
      options:
        - label:  I have searched the existing issues
    validations:
       required: true
  - type: textarea
    attributes:
      label: Why is this feature needed/good for the game?
      description: A clear and concise description of why this feature is needed. You can describe the problem it solves, or the benefit it brings.
      placeholder: I'm always frustrated when I can't hug the clown without it exploding.
    validations:
      required: true
  - type: textarea
    attributes:
      label: User Story
      description: Write a short green-text story for this feature. A green-text story is straight-forward multi-line story composed of single sentences that describes actions.
      value: |
        > Be security officer.
        > Slip clown on a banana-flavored donut 
        > Clown explodes.
        > mfw
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: What other solutions have you considered? What other features are similar to this one? What would be the downsides of this feature?
      placeholder: I considered making the clown hug me back, but that would be too much work.
    validations:
      required: false
